$ANSIBLE_VAULT;1.1;AES256
62383639303763643733663731333365643634343866626238646564613165646336343832333663
3762356662653035316135366535666463663762333533650a383562353062333536383739653034
66653962316635356332383666356539396466613037323762643330393764653266356364336539
3636326334616562350a346562336139636366623361353763303961326562326266333330306438
38613036326434373836383765633535333530646263376461343262316232663436363334626438
3764656432366332366631653934383830633336623938373239