$ANSIBLE_VAULT;1.1;AES256
65333634326366653564373365376233643931336564343831616431343432376465666363303232
3163366235636230333466306535653534323665373466640a313138323638303732643130326636
38643262366138393362313138646664333262656236393162393162616261313338353733303664
6435376137373235310a653364303333333938323339373463653839356162383434343537373538
66326639353334373830343062653565666132646463303230343464353730373232